### ISSUE TITLE
Update DID - JSON Exception

### ISSUE THREAD

**Issue by danexpo** [michaelkourlas/voipms-sms#9]
When attempting to select a DID, a popup appears that says: "Update DID: Unable to parse VoIP.ms api response (jsonexception).

**Comment by danexpo** [comment]
Issue was resolved by removing INUM DID from account.

**Comment by fcastilloec** [comment]
I'm seeing this error with the last update too. I'm not able to confirm that the problem is solved by removing the INUM DID, since I use that DID.

**Comment by borfo** [comment]
I'm seeing the same error when I try to select a DID.  I tried removing (deleting) my INUM DID from my account, but I'm still seeing the error.  I have the following DIDs remaining on my account: 1 x 1-800 us/canada number, 1 x UK (London) number, 3 x Toronto local numbers, and 1 x NYC number

Thanks for the update, even though it's not usable for me yet since I can't select a DID.

**Comment by michaelkourlas** [comment]
Unfortunately, "JSONException" is too general for me to debug. I can try adding an INUM DID to my account and seeing what happens, though. I'll also update the app with a more robust logging mechanism so the next time you see that error, you'll be able to send me logs that I can use to diagnose the problem.

**Comment by borfo** [comment]
Thanks.  I'll report back once the debugging log thing is in place.

Looks like the error message happens at line 329 of /src/main/java/net/kourlas/voipms_sms/api.java

**Comment by michaelkourlas** [comment]
Good news! I've figured out what the problem is. The app wasn't checking to see if SMS was available for a DID before checking if it was enabled.

I'll release an updated version shortly.

**Comment by michaelkourlas** [comment]
Done! Check Google Play in a few hours.
